server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
    
    
spring:
  application:
    name: booking-service    
  cloud:
    loadbalancer:
      retry:
        enabled: true
    stream:
      bindings:
        cargoBookingChannel:
          destination: cargoBookings          
          binder: rabbit
        cargoRoutingChannel:
          destination: cargoRoutings         
          binder: rabbit
        cargoHandlingChannel:
          destination: cargoHandling
          group: cargoHandlingInBookingQueue
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver