server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}



spring:
  application:
    name: routing-service
    
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
