server:
  port: 8082

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:5001/eureka
#Eureka-cluster
      defaultZone: http://eureka-primary:4002/eureka
#TCP/IP monitoring
#      defaultZone: http://localhost:1234/eureka
#      z1: http://localhost:5001/eureka
#      z2: http://localhost:5001/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60


spring:
  application:
    name: routing-service
    
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
